name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - sandbox
  pull_request:

env:
  AWS_REGION: us-east-1
  STACK_NAME: my-app

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Deploy Stack
        run: |
          cdk deploy ${STACK_NAME} --require-approval never || {
            echo '❌ Deployment failed. Checking rollback options...';
            if [ "$AUTO_ROLLBACK" == "yes" ]; then
              echo '🔄 Rolling back...';
              aws cloudformation rollback-stack --stack-name ${STACK_NAME}
            else
              echo '🛑 Manual rollback required!';
            fi
          }

      - name: Set CloudWatch Log Retention
        run: |
          aws logs put-retention-policy --log-group-name "/ci-cd/rollbacks" --retention-in-days $LOG_RETENTION_DAYS
